"""add columns to table

Revision ID: 182d26655307
Revises: f68daa2f3bc5
Create Date: 2023-09-24 17:08:12.924553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182d26655307'
down_revision = 'f68daa2f3bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('image')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
